IF(XDYN_NATIVE_BUILD)
    FIND_PACKAGE(Eigen3 REQUIRED)
    GET_TARGET_PROPERTY(eigen_INCLUDE_DIRS Eigen3::Eigen INTERFACE_INCLUDE_DIRECTORIES)
    # eigen3-hdf5 is header-only and not packaged anywhere; it is a submodule here
    SET(eigen_hdf5_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/external/eigen3-hdf5)
ELSE()
    SET(eigen_INCLUDE_DIRS ${THIRD_PARTY_DIRECTORY}/eigen)
    SET(eigen_hdf5_INCLUDE_DIRS ${THIRD_PARTY_DIRECTORY}/eigen3-hdf5)
ENDIF()
# ADD_DEFINITIONS(-DEIGEN_DONT_VECTORIZE) # Cf. http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html
# ADD_DEFINITIONS(-DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT)
IF(CMAKE_BUILD_TYPE_UPPER MATCHES RELEASE)
    ADD_DEFINITIONS(-DEIGEN_NO_DEBUG)
ENDIF()
