issue_202: demos
	@echo "Running simulation for issue 202..."
	@cd $(WORK) && $(XDYN) issue_202.yml --dt 1 --tend 2
	@echo "Checking forces & torques are outputted in the right frame (issue #202)"
	@cd $(WORK) && $(PYTHON) issue_202.py
	@echo "✓ Output is correct!"
